<a href="https://colab.research.google.com/github/Anuk17/classroom/blob/master/k_nearest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import pairwise_distances
import numpy as np
from scipy.stats import mode
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

iris = datasets.load_iris()
X = iris.data  # Features
y = iris.target  # Target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=41)

distances = pairwise_distances(X_train, metric='euclidean')  # Specify the metric as 'euclidean'

def find_k_nearest_neighbors(distances, k):
    k_nearest_neighbors_indices = np.argsort(distances, axis=1)[:, :k]
    return k_nearest_neighbors_indices

k = 5
k_nearest_neighbors_indices = find_k_nearest_neighbors(distances, k)

def predict_majority_class(k_nearest_neighbors_indices, y_train):
    k_nearest_classes = y_train[k_nearest_neighbors_indices]
    predictions, _ = mode(k_nearest_classes, axis=1)
    return predictions.ravel()

# Use k_nearest_neighbors_indices to index y_train directly
y_pred = predict_majority_class(k_nearest_neighbors_indices, y_train)

# Only consider the first len(y_test) predictions
y_pred = y_pred[:len(y_test)]

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Accuracy: 0.26666666666666666

Classification Report:
              precision    recall  f1-score   support

           0       0.20      0.36      0.26        11
           1       0.33      0.22      0.27        18
           2       0.31      0.25      0.28        16

    accuracy                           0.27        45
   macro avg       0.28      0.28      0.27        45
weighted avg       0.29      0.27      0.27        45


Confusion Matrix:
[[4 3 4]
 [9 4 5]
 [7 5 4]]
